-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 14:35:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoSuscripciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoSuscripciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoSuscripciones` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoSuscripciones` ;

-- -----------------------------------------------------
-- Table `ProyectoSuscripciones`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSuscripciones`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `direction` VARCHAR(45) NOT NULL,
  `percentageAdmin` DOUBLE NOT NULL,
  `percentageSucursal` DOUBLE NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSuscripciones`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSuscripciones`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `user_type` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_User_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `ProyectoSuscripciones`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSuscripciones`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSuscripciones`.`Subscription` (
  `idSubscription` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idSubscription`),
  INDEX `fk_Subscription_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Subscription_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ProyectoSuscripciones`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSuscripciones`.`SubscriptionPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSuscripciones`.`SubscriptionPlan` (
  `idSubscriptionPlan` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `Subscription_idSubscription` INT NOT NULL,
  PRIMARY KEY (`idSubscriptionPlan`),
  INDEX `fk_SubscriptionPlan_Subscription1_idx` (`Subscription_idSubscription` ASC) VISIBLE,
  CONSTRAINT `fk_SubscriptionPlan_Subscription1`
    FOREIGN KEY (`Subscription_idSubscription`)
    REFERENCES `ProyectoSuscripciones`.`Subscription` (`idSubscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSuscripciones`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSuscripciones`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `payment_date` DATE NOT NULL,
  `Subscription_idSubscription` INT NOT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `fk_Payment_Subscription1_idx` (`Subscription_idSubscription` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Subscription1`
    FOREIGN KEY (`Subscription_idSubscription`)
    REFERENCES `ProyectoSuscripciones`.`Subscription` (`idSubscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoSuscripciones`.`Comition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoSuscripciones`.`Comition` (
  `idComition` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `comition_date` DATE NOT NULL,
  `Subscription_idSubscription` INT NOT NULL,
  PRIMARY KEY (`idComition`),
  INDEX `fk_Comition_Subscription1_idx` (`Subscription_idSubscription` ASC) VISIBLE,
  CONSTRAINT `fk_Comition_Subscription1`
    FOREIGN KEY (`Subscription_idSubscription`)
    REFERENCES `ProyectoSuscripciones`.`Subscription` (`idSubscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
